// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTDc7ooqhhH52l-LKB-Ag1_D1i9Or7D1c',
    appId: '1:905948571532:web:6829568c148255574dd8a9',
    messagingSenderId: '905948571532',
    projectId: 'auliya-79612',
    authDomain: 'auliya-79612.firebaseapp.com',
    storageBucket: 'auliya-79612.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNxiTaLTqVZsDozyYXok0WKBFfnLYjg8M',
    appId: '1:905948571532:android:a38c88e019bf7a924dd8a9',
    messagingSenderId: '905948571532',
    projectId: 'auliya-79612',
    storageBucket: 'auliya-79612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIAFqOF5L0AcATA3w20Qdt7m_5v5cE93A',
    appId: '1:905948571532:ios:20860eb702012e564dd8a9',
    messagingSenderId: '905948571532',
    projectId: 'auliya-79612',
    storageBucket: 'auliya-79612.firebasestorage.app',
    iosBundleId: 'com.example.auliya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIAFqOF5L0AcATA3w20Qdt7m_5v5cE93A',
    appId: '1:905948571532:ios:20860eb702012e564dd8a9',
    messagingSenderId: '905948571532',
    projectId: 'auliya-79612',
    storageBucket: 'auliya-79612.firebasestorage.app',
    iosBundleId: 'com.example.auliya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTDc7ooqhhH52l-LKB-Ag1_D1i9Or7D1c',
    appId: '1:905948571532:web:65b29739e65dc0894dd8a9',
    messagingSenderId: '905948571532',
    projectId: 'auliya-79612',
    authDomain: 'auliya-79612.firebaseapp.com',
    storageBucket: 'auliya-79612.firebasestorage.app',
  );
}
